feature:
  - head-branch: ['^feature/']
fix:
  - head-branch: ['^fix/', '^bugfix/', '^hotfix/']
documentation:
  - head-branch: ['^documentation/']
refactor:
  - head-branch: ['^refactor/']
performance:
  - head-branch: ['^performance/']
test:
  - head-branch: ['^test/']
ci:
  - head-branch: ['^ci/', '^pipeline/']
build:
  - head-branch: ['^build/']
chore:
  - head-branch: ['^chore/']
revert:
  - head-branch: ['^revert/']
style:
  - head-branch: ['^style/']
